services:
  mc-proxy:
    build: .
    ports:
      - "30000:30000"
    volumes:
      - mc-world-data:/app/minecraft-server/world
      - mc-logs:/app/minecraft-server/logs

volumes:
  mc-world-data:
  mc-logs: